### ISSUE TITLE
which version KYPO

### ISSUE THREAD

**Issue by k1ll50m30n3** [vydrazde/terraform-provider-kypo#33]
Do you use the "KYPO CRP" or "KYPO-CRP-LITE" version?

**Comment by vydrazde** [comment]
I use the latest KYPO CRP, haven't tested with KYPO CRP Lite, but I don't see why it would be any different.

**Comment by k1ll50m30n3** [comment]
Hi support team,

Ok, but I tried to install the latest version of KYPO-CRP many times but
still got the "imageloopbackoff" error. Can you make a detailed tutorial
for me? Or can I record my installation and send it to you?.

I will be very grateful if I get your help.

Regards,

Vào 18:04, Th 2, 21 thg 8, 2023 Zdeněk Vydra ***@***.***> đã
viết:

**Comment by vydrazde** [comment]
Sorry, this is not KYPO support; this is a Terraform provider for KYPO. If you have questions or issues with the Terraform provider, please open another issue.
